$baseUrl = "https://fds-cnbj1-mcfe-cdn.micloud.xiaomi.net/archive/download/full-release/win32/x64/XiaomiCloud-{0}.exe"

# 生成版本号 1.0.0 ~ 9.9.9
$versions = foreach ($major in 1..9) {
    foreach ($minor in 0..0) {
        foreach ($patch in 0..9) {
            "{0}.{1}.{2}" -f $major, $minor, $patch
        }
    }
}

$Throttle = 8   # 并行线程数，可根据 CPU/网络调整

$versions | ForEach-Object -Parallel {
    $baseUrl = $using:baseUrl
    $url = $baseUrl -f $_

    try {
        $response = Invoke-WebRequest -Uri $url -Method Head -TimeoutSec 5 -ErrorAction Stop
        Write-Host "✔ $url Available ($($response.StatusCode))" -ForegroundColor Green
    }
    catch {
        Write-Host "✘ $url Not available" -ForegroundColor Red
    }
} -ThrottleLimit $Throttle

# GENERATED BY COPILOT